# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0042_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('composer', 'Composer'), ('band', 'Band')], default='composer', max_length=20, verbose_name='template'),
            preserve_default=False,
        ),
    ]
