# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0043_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='post',
            name='link_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='link text'),
        ),
    ]
