# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0044_auto_20170928_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(help_text='Name of the member', max_length=100, verbose_name='name')),
                ('description', models.CharField(help_text='Role(s) or description', max_length=200, verbose_name='description')),
                ('mugshot', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='uploads/%Y-%m-%d/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Page')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
