# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0045_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='roles',
            field=models.CharField(default='guitar', max_length=60, verbose_name='roles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, help_text='Description', max_length=200, null=True, verbose_name='description'),
        ),
    ]
