# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0047_page_youtube_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='youtube_playlist',
            field=models.CharField(blank=True, help_text='ID of the YouTube playlist, e.g. PLjZN_n5TZFcxOHUG3TTDbAe4Z_Qz6SuTw', max_length=30, null=True),
        ),
    ]
