# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0050_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
    ]
