# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0051_auto_20170928_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
