# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0054_auto_20170928_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='extra_copyright_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
