# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0056_auto_20170928_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='domain',
            field=models.CharField(default='example.com', max_length=40),
            preserve_default=False,
        ),
    ]
