# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0058_page_about_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=200, null=True, verbose_name='description'),
        ),
    ]
