# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0059_auto_20170929_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='kind',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('bandcamp', 'BandCamp'), ('vevo', 'Vevo'), ('itunes', 'iTunes'), ('lastfm', 'LastFM'), ('tumblr', 'Tumblr')], max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='body'),
        ),
    ]
