# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0060_auto_20170929_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='body'),
        ),
    ]
