# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0061_auto_20170929_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, help_text='Descript or bio', max_length=400, null=True, verbose_name='description'),
        ),
    ]
