# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0062_auto_20170929_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
    ]
