# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0063_page_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='media_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
    ]
