# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0065_auto_20171003_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedded_content',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
