# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0066_auto_20171003_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',), 'verbose_name': 'news post'},
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, help_text='Description or bio', max_length=400, null=True, verbose_name='description'),
        ),
    ]
