# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0067_auto_20171003_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='instagram_access_token',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='kind',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('bandcamp', 'BandCamp'), ('vevo', 'Vevo'), ('itunes', 'iTunes'), ('lastfm', 'LastFM'), ('tumblr', 'Tumblr'), ('instagram', 'Instagram')], max_length=20, verbose_name='kind'),
        ),
    ]
