# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0068_auto_20180903_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedcontent',
            name='content',
            field=models.TextField(help_text='Paste in the embedded content from SoundCloud / YouTube etc.', max_length=4000),
        ),
        migrations.AlterField(
            model_name='page',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
