# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0070_auto_20180904_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedcontent',
            name='kind',
            field=models.CharField(choices=[('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('bandcamp', 'BandCamp'), ('vevo', 'Vevo'), ('itunes', 'iTunes'), ('lastfm', 'LastFM'), ('tumblr', 'Tumblr'), ('instagram', 'Instagram')], default='embedded', max_length=20, verbose_name='kind'),
        ),
        migrations.AddField(
            model_name='embeddedcontent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=portfolios.models.get_upload_path, verbose_name='thumbnail'),
        ),
    ]
