# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0072_page_number_of_featured_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedcontent',
            name='content',
            field=models.TextField(help_text='Paste in the embedded content from SoundCloud / YouTube etc.', max_length=16000),
        ),
    ]
